swagger: "2.0"
info:
  description: "Api todo"
  version: "1.0.0"
  title: "Todo"
host: "localhost:5000"
basePath: "/"
tags:
- name: "todo"
  description: "Swagger todo"
schemes:
- "https"
- "http"
paths:
  /todo:
    get:
      summary: "Get todo"
      operationId: "getTodo"
      tags:
      - "todo"
      responses:
        "200":
          description: "Get todo"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Todo"
        "400":
          description: "Bad request"
        "500":
          description: "Forbidden request"
    post:
      tags:
      - "todo"
      summary: "Add todo"
      operationId: "addTodo"
      parameters:
      - in: "body"
        name: "body"
        description: "Add todo"
        required: true
        schema:
          type: "object"
          properties:
            text:
              type: "string"
              description: "content"
      responses:
        "200":
          description: "Todo added"
          schema:
            $ref: "#/definitions/Todo"
        "400":
          description: "Bad request"
        "500":
          description: "Forbidden request"
  /todo/{id}:
    patch:
      tags:
      - "todo"
      summary: "Patch todo"
      description: "Patch todo"
      operationId: "patchTodo"
      parameters:
      - in: "path"
        name: "id"
        description: "Id todo to patch"
        required: true
        type: integer
      responses:
        "200":
          description: "Todo patched"
          schema:
            $ref: "#/definitions/Todo"
        "400":
          description: "Bad request"
        "500":
          description: "Forbidden request"


definitions:
  Todo:
    type: object
    properties:
      id:
        type: "integer"
        description: "id todo"
      text:
        type: "string"
        description: "content"
      done:
        type: "boolean"
        description: "true if todo is complete"